# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateTimeField(default='2000-05-01'),
            preserve_default=False,
        ),
    ]
