# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler', to='loginapp.Users')),
            ],
            managers=[
                ('userTripsManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='planner',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='traveler',
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default='no destination', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='loginapp.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.AddField(
            model_name='usertrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='travelapp.Trip'),
        ),
    ]
